name: create cucumber shell script with kotlin
description:
  "Generates a shell script by running script navikt/bidrag-scripts/src/kotlin/createCucumberShell.kts.
  Expects:
    - that the kotlin script are found in the src/kotlin path of this repository
    - that generated file are found in RUNNER_WORKSPACE
    - if the generated scripts needs arguments, then 2 input argumentss on the kotlin script are expected
      1) delimiter (ex: ,)
      2) string of arguments separated by delimiter (ex: arg1,arg2,...,argx)"
runs:
  using: node12
  main: dist/index.js
inputs:
  cucumber_github_project:
    description: The name of the cucumber github project
    required: true
    default: bidrag-cucumber-backend
  cucumber_tag:
    description: The cucumber tag to use when running integration tests suite
    required: false
  do_not_fail:
    description: The cucumber integration test suite should not cause a workflow failure when tests have errors
    required: true
    default: "false"
  final_shell_name:
    description: The name of the shell file created
    required: true
    default: execute-cucumber.sh
  maven_goal:
    description: The goeal used to run tests with maven
    required: true
    default: test
  optional_maven_goal:
    description: An optional maven goal
    required: false
  relative_json_path:
    description: inputs containing evironment, username for test user, relative nais_project_folder, and azure credentials for apps secured with azure
    required: true
    default: json/integrationInput.json
  user:
    description: user name of nav user running the cucumber tests
    required: true
outputs:
  created_shell:
    description: the filepath to the created shell
